//! Generates `thresholds_generated.rs` from the workspace's `thresholds.toml` (D17,
//! IMPLEMENTATION_PLAN §1.5 and Phase 0 detail 6).
//!
//! The output goes to `OUT_DIR` and is pulled in with `include!`, rather than being written
//! into `src/` as §1.5's prose suggests: a build script that writes into its own source tree
//! breaks read-only and vendored builds, and Cargo warns about it. The generated text is
//! still inspectable — `target/<profile>/build/oc-core-*/out/thresholds_generated.rs`.
//!
//! This script only rejects entries that are *malformed*. Whether a `provisional` entry has
//! an owner and an unexpired `review_by` is a lint, not a build error, because a build that
//! starts failing on a date nobody touched is a bad way to learn that: that rule lives in
//! `oc_core::thresholds::lint`, is asserted by a test, and is run by `xtask thresholds-lint`.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::PathBuf;

/// The schema version this build script understands.
const SUPPORTED_SCHEMA_VERSION: i64 = 1;

/// Marks a TOML table as a threshold entry rather than a namespace.
const VALUE_KEY: &str = "value";

const SCHEMA_VERSION_KEY: &str = "schema_version";

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let thresholds_path = manifest_dir.join("../../thresholds.toml");

    println!("cargo:rerun-if-changed={}", thresholds_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let text = std::fs::read_to_string(&thresholds_path)
        .unwrap_or_else(|e| fail(&format!("cannot read {}: {e}", thresholds_path.display())));
    let root: toml::Value = toml::from_str(&text).unwrap_or_else(|e| {
        fail(&format!(
            "{} is not valid TOML: {e}",
            thresholds_path.display()
        ))
    });

    let table = root
        .as_table()
        .unwrap_or_else(|| fail("thresholds.toml must be a table"));

    match table
        .get(SCHEMA_VERSION_KEY)
        .and_then(toml::Value::as_integer)
    {
        Some(SUPPORTED_SCHEMA_VERSION) => {}
        Some(other) => fail(&format!(
            "thresholds.toml declares schema_version {other}; this build understands \
             {SUPPORTED_SCHEMA_VERSION}"
        )),
        None => fail("thresholds.toml has no integer schema_version"),
    }

    let mut namespaces = Vec::new();
    let mut provenance = Vec::new();
    let root_type = collect(table, &[], &mut namespaces, &mut provenance);
    // Depth-first order already matches dotted order for the current key set, but sorting
    // says so rather than relying on it.
    provenance.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::new();
    out.push_str(
        "// @generated by crates/oc-core/build.rs from thresholds.toml. Do not edit.\n\
         // Every value carries provenance in PROVENANCE; see docs/DECISIONS.md D17.\n\n",
    );
    for namespace in &namespaces {
        out.push_str(&namespace.render_struct());
    }
    let _ = writeln!(
        out,
        "/// Every threshold, resolved at build time from `thresholds.toml`.\n\
         pub static T: {root_type} = {};\n",
        namespaces
            .iter()
            .find(|n| n.type_name == root_type)
            .unwrap_or_else(|| fail("no root namespace"))
            .render_value()
    );
    out.push_str(
        "/// `(dotted key, source, evidence)` for every entry, sorted by key. Emitted into\n\
         /// the conversion report so a reader can see which numbers were provisional.\n\
         pub static PROVENANCE: &[(&str, &str, &str)] = &[\n",
    );
    for (key, source, evidence) in &provenance {
        let _ = writeln!(
            out,
            "    ({}, {}, {}),",
            quote(key),
            quote(source),
            quote(evidence)
        );
    }
    out.push_str("];\n");

    let out_path =
        PathBuf::from(std::env::var_os("OUT_DIR").unwrap_or_else(|| fail("OUT_DIR is not set")))
            .join("thresholds_generated.rs");
    std::fs::write(&out_path, out)
        .unwrap_or_else(|e| fail(&format!("cannot write {}: {e}", out_path.display())));
}

/// One generated struct: a table in `thresholds.toml` that is not itself an entry.
struct Namespace {
    type_name: String,
    /// Field name → (field type, initialiser expression). `BTreeMap` so the generated file
    /// is byte-identical for the same input.
    fields: BTreeMap<String, (String, String)>,
}

impl Namespace {
    fn render_struct(&self) -> String {
        let mut out = format!(
            "#[derive(Debug, Clone, Copy)]\npub struct {} {{\n",
            self.type_name
        );
        for (name, (ty, _)) in &self.fields {
            let _ = writeln!(out, "    pub {name}: {ty},");
        }
        out.push_str("}\n\n");
        out
    }

    fn render_value(&self) -> String {
        let mut out = format!("{} {{ ", self.type_name);
        for (name, (_, value)) in &self.fields {
            let _ = write!(out, "{name}: {value}, ");
        }
        out.push('}');
        out
    }
}

/// Walk a namespace table, emitting a `Namespace` for it and for every namespace beneath
/// it, and returning its generated type name.
fn collect(
    table: &toml::Table,
    path: &[String],
    namespaces: &mut Vec<Namespace>,
    provenance: &mut Vec<(String, String, String)>,
) -> String {
    let mut fields = BTreeMap::new();

    for (key, value) in table {
        if path.is_empty() && key == SCHEMA_VERSION_KEY {
            continue;
        }
        check_identifier(key, path);

        let child = value.as_table().unwrap_or_else(|| {
            fail(&format!(
                "{} must be a table: every threshold is a table of \
                 {{value, source, evidence, owner, review_by}}",
                dotted(path, key)
            ))
        });

        let mut child_path = path.to_vec();
        child_path.push(key.clone());

        if child.contains_key(VALUE_KEY) {
            let entry = read_entry(child, &child_path);
            fields.insert(key.clone(), (entry.rust_type, entry.rust_value));
            provenance.push((dotted(path, key), entry.source, entry.evidence));
        } else {
            let type_name = collect(child, &child_path, namespaces, provenance);
            fields.insert(
                key.clone(),
                (type_name.clone(), format!("{type_name}_VALUE")),
            );
        }
    }

    // Nested namespaces are initialised inline, so patch the placeholder now that every
    // child namespace has been rendered.
    for (ty, value) in fields.values_mut() {
        if let Some(name) = value.strip_suffix("_VALUE") {
            if name == ty {
                *value = namespaces
                    .iter()
                    .find(|n| &n.type_name == ty)
                    .unwrap_or_else(|| fail(&format!("namespace {ty} was not generated")))
                    .render_value();
            }
        }
    }

    let type_name = type_name_for(path);
    namespaces.push(Namespace {
        type_name: type_name.clone(),
        fields,
    });
    type_name
}

struct Entry {
    rust_type: String,
    rust_value: String,
    source: String,
    evidence: String,
}

fn read_entry(table: &toml::Table, path: &[String]) -> Entry {
    let key = path.join(".");
    let string_field = |name: &str| -> String {
        table
            .get(name)
            .and_then(toml::Value::as_str)
            .unwrap_or_else(|| fail(&format!("{key} has no string `{name}`")))
            .to_owned()
    };

    let source = string_field("source");
    if !matches!(
        source.as_str(),
        "binary" | "published" | "provisional" | "calibrated"
    ) {
        fail(&format!(
            "{key} has source \"{source}\"; D17 allows binary, published, provisional, calibrated"
        ));
    }
    let evidence = string_field("evidence");
    // `owner` must be present on every entry; whether it may be empty is the lint's business.
    let _ = string_field("owner");

    let (rust_type, rust_value) = match table.get(VALUE_KEY) {
        Some(toml::Value::Float(f)) => ("f64".to_owned(), format!("{f:?}f64")),
        Some(toml::Value::Integer(i)) => ("i64".to_owned(), format!("{i}i64")),
        Some(toml::Value::Boolean(b)) => ("bool".to_owned(), b.to_string()),
        Some(other) => fail(&format!(
            "{key} has value of type {}; thresholds are floats, integers or booleans",
            other.type_str()
        )),
        None => fail(&format!("{key} has no value")),
    };

    Entry {
        rust_type,
        rust_value,
        source,
        evidence,
    }
}

fn type_name_for(path: &[String]) -> String {
    if path.is_empty() {
        return "Thresholds".to_owned();
    }
    path.iter()
        .flat_map(|segment| segment.split('_'))
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn dotted(path: &[String], key: &str) -> String {
    if path.is_empty() {
        key.to_owned()
    } else {
        format!("{}.{key}", path.join("."))
    }
}

fn check_identifier(key: &str, path: &[String]) {
    let valid = !key.is_empty()
        && !key.starts_with(|c: char| c.is_ascii_digit())
        && key
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_');
    if !valid {
        fail(&format!(
            "{} is not a usable Rust field name; threshold keys are lower_snake_case",
            dotted(path, key)
        ));
    }
}

fn quote(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for ch in text.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            other => out.push(other),
        }
    }
    out.push('"');
    out
}

/// Abort the build with a message the developer can act on. A build script has no error
/// channel other than exiting, so this never returns.
fn fail(message: &str) -> ! {
    println!("cargo:warning=thresholds.toml: {message}");
    eprintln!("thresholds.toml: {message}");
    std::process::exit(1)
}
